export enum MapPresetId {
  ESRI_SAT_LABELS     = 'esri-sat-labels',
  CARTO_DARK          = 'carto-dark',
  CARTO_DARK_NOLABELS = 'carto-dark-nolabels',
  CARTO_LIGHT         = 'carto-light',
  CARTO_VOYAGER       = 'carto-voyager',
  OSM                 = 'osm',
  WIKIMEDIA           = 'wikimedia',
  HOT                 = 'hot',
  CYCLOSM             = 'cyclosm',
  OPENTOPOMAP         = 'opentopomap',
  ESRI_TOPO           = 'esri-topo',
  ESRI_STREET         = 'esri-street',
  ESRI_NATGEO         = 'esri-natgeo',
  ESRI_SATELLITE      = 'esri-satellite',
  STADIA_DARK         = 'stadia-dark',
  ESRI_GRAY           = 'esri-gray',
}
